---
# tasks file for fedora-workstation

- include_tasks: repositories.yml
  tags:
    - repositories

- include_tasks: packages.yml
  tags:
    - packages

- include_tasks: users.yml
  when: fedora_workstation_users is defined
  with_items: "{{ fedora_workstation_users }}"
  tags:
   - users

- include_tasks: sudo.yml
  tags:
    - sudo

- include_tasks: autofs.yml
  tags:
    - autofs

- include_tasks: vpn.yml
  tags:
    - vpn

