---
- name: enable jbertozzi's COPR repository
  command: dnf copr enable jbertozzi/gnome-shell-extensions -y

- name: enable cisco openh264 repository
  command: dnf config-manager --set-enabled fedora-cisco-openh264

#dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
- name: enable rpmfusion repositories
  dnf:
    name: 
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: enable adobe repository
  dnf:
    state: present
    name:  http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm
    disable_gpg_check: true
    
